### ISSUE TITLE
spurious courses in JSON exports from CHASS

### ISSUE THREAD

**Issue by jmzaleski** [uoft-tapp/old-orig-tapp#141]
We are starting to work with the data from the application system.  I noticed a couple of problems.  Neither of them are show stoppers.

1) The data from the field Will you be enrolled as a U of T graduate student for the TA session?” doesn’t seem to appear in the JSON file.

2) Some courses appear in the JSON output that aren’t part of the round.  For example, the following appears in the JSON data but this course is not checked in the Main Round view in the web applications.  There are a few of these.

{"course_id":"CSC104H1S","course_name":"Computational Thinking","round_id":”110”, …

**Comment by alynch** [comment]
1. Added missing field; the id is `full_time`.

2. Removed inactive courses for a round. (The root cause is that if a course is selected for a round, and posting information is entered, and then we remove that course, the system does not delete it but sets a flag as `inactive` so that we don't lose information in case we want to re-enable that course for the round. The system was displaying all courses, active and inactive.)

**Comment by reidka** [comment]
Looks great!  Thanks.
