### ISSUE TITLE
Find out if Alejandro can include date of application field in each Applicant in the export JSON file

### ISSUE THREAD

**Issue by jmzaleski** [uoft-tapp/old-orig-tapp#8]
This might be nothing but a conversation to make sure he knows we want it.

**Comment by alynch** [comment]
We have a timestamp for last update. However, applications are open until the deadline, so applicants can review and modify it several times is they want, and our application will only keep track of the last modification time. 

We could add a creation date so that we know when was the original submission, if necessary.
